#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ALLBOT.Droid.Resource", IsApplication=true)]

namespace ALLBOT.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int Columns = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int Presets = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int Selected = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int apptheme_color = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int PresetFontSize = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int apptheme_scrubber_control_disabled_holo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int apptheme_scrubber_control_focused_holo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int apptheme_scrubber_control_normal_holo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int apptheme_scrubber_control_pressed_holo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int apptheme_scrubber_control_selector_holo_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int apptheme_scrubber_primary_holo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int apptheme_scrubber_progress_horizontal_holo_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int apptheme_scrubber_secondary_holo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int apptheme_scrubber_track_holo_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bol_green = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bol_white = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int dpad = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int dpad_rotated = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_appicon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int logo = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int round_buttton = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int sliderbackground = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int sliderbutton = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int MainLayout = 2131296256;
			
			// aapt resource value: 0x7f09000e
			public const int PresetLayoutHelper = 2131296270;
			
			// aapt resource value: 0x7f090008
			public const int Presets = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int dpad = 2131296263;
			
			// aapt resource value: 0x7f090006
			public const int linControls = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int linNames = 2131296258;
			
			// aapt resource value: 0x7f09000a
			public const int linVersion = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int seekBar1 = 2131296265;
			
			// aapt resource value: 0x7f09000c
			public const int textVersion = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int textVersionNumber = 2131296269;
			
			// aapt resource value: 0x7f09000b
			public const int textscreensize = 2131296267;
			
			// aapt resource value: 0x7f090003
			public const int txtAction = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int txtPreset = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int txtSpeed = 2131296261;
			
			// aapt resource value: 0x7f090001
			public const int txtTitle = 2131296257;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080002
			public const int AppTheme = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int MyCustomTheme = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int SeekBarAppTheme = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int _AppTheme = 2131230723;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PresetButton = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int PresetButton_Selected = 0;
			
			public static int[] PresetsLayout = new int[] {
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int PresetsLayout_Columns = 1;
			
			// aapt resource value: 0
			public const int PresetsLayout_Presets = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
