#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ALLBOT.Resource", IsApplication=true)]

namespace ALLBOT
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int Columns = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int Presets = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int Selected = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int PresetFontSize = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int SeekBarHeight = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int SeekBarWidth = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bol_green = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bol_white = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int COMPOSED = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dpad = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int dpad_rotated = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int round_buttton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sliderbackground = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sliderbutton = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int MainLayout = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int Presets = 2131165192;
			
			// aapt resource value: 0x7f07000e
			public const int SeekBarLayoutHelper = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int dpad = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int linControls = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int linNames = 2131165186;
			
			// aapt resource value: 0x7f07000a
			public const int linVersion = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int seekBar1 = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int textVersion = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int textVersionNumber = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int textscreensize = 2131165195;
			
			// aapt resource value: 0x7f070003
			public const int txtAction = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int txtPreset = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int txtSpeed = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int txtTitle = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyCustomTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PresetButton = new int[]
			{
					2130771968};
			
			// aapt resource value: 0
			public const int PresetButton_Selected = 0;
			
			public static int[] PresetsLayout = new int[]
			{
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int PresetsLayout_Columns = 1;
			
			// aapt resource value: 0
			public const int PresetsLayout_Presets = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
